/**
 * GET /api/v1/remote-aob/[token]/summary
 *
 * Public, unauthenticated by design — same posture as the signing page
 * itself and remote_aob_links' own RLS (anon-readable). Lets the remote
 * signing page show AobAgreementText's vehicle/claim header without the
 * page's own anon Supabase client trying to read intake_leads directly,
 * which is now org-scoped RLS and would just return nothing.
 *
 * Strictly token-keyed: the ONLY input this route accepts is the token in
 * the URL. lead_id is resolved server-side from remote_aob_links by that
 * token — never accepted as a parameter, request body, or query string, so
 * there is no way for a caller to ask this route for a different lead's
 * data than the one their token actually authorizes. This uses a
 * service-role client and is reachable by anyone with the URL; treat every
 * input as hostile.
 *
 * Returns only the fields AobAgreementText needs — not the full lead row.
 *
 * 200: { customerName, vehicleYear, vehicleMake, vehicleModel, vinLast8,
 *        claimNumber, insuranceCarrier, policyNumber }
 * 404: { error: string }   (bad token, or the lead it points to is gone)
 */
import { NextResponse } from 'next/server';
import { createSupabaseServerClient } from '@/lib/supabase-server';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

// remote_aob_links.token is generated by genToken() in remote-aob-db.ts as
// either a 32-char hex string (crypto.randomUUID with dashes stripped) or a
// digits-only fallback — bound the accepted shape tightly rather than
// forwarding whatever arrives straight into a query.
const TOKEN_RE = /^[a-z0-9]{1,64}$/i;

interface LeadSummaryRow {
  customer_name: string | null;
  vehicle_year: number | null;
  vehicle_make: string | null;
  vehicle_model: string | null;
  vin_last8: string | null;
  claim_number: string | null;
  insurance_carrier: string | null;
  policy_number: string | null;
}

export async function GET(
  _request: Request,
  { params }: { params: Promise<{ token: string }> },
): Promise<Response> {
  const { token } = await params;

  if (!token || !TOKEN_RE.test(token)) {
    return NextResponse.json({ error: 'Invalid token.' }, { status: 404 });
  }

  const supabase = createSupabaseServerClient();

  const { data: link, error: linkError } = await supabase
    .from('remote_aob_links')
    .select('lead_id')
    .eq('token', token)
    .maybeSingle();
  if (linkError || !link) {
    return NextResponse.json({ error: 'Signing link not found.' }, { status: 404 });
  }
  const leadId = (link as { lead_id: string }).lead_id;

  const { data: lead, error: leadError } = await supabase
    .from('intake_leads')
    .select(
      'customer_name, vehicle_year, vehicle_make, vehicle_model, vin_last8, claim_number, insurance_carrier, policy_number',
    )
    .eq('id', leadId)
    .maybeSingle();
  if (leadError || !lead) {
    return NextResponse.json({ error: 'Lead not found.' }, { status: 404 });
  }
  const row = lead as unknown as LeadSummaryRow;

  return NextResponse.json({
    customerName: row.customer_name ?? undefined,
    vehicleYear: row.vehicle_year ?? undefined,
    vehicleMake: row.vehicle_make ?? undefined,
    vehicleModel: row.vehicle_model ?? undefined,
    vinLast8: row.vin_last8 ?? undefined,
    claimNumber: row.claim_number ?? undefined,
    insuranceCarrier: row.insurance_carrier ?? undefined,
    policyNumber: row.policy_number ?? undefined,
  });
}
