/**
 * MESH — sample insurance supplement records.
 *
 * Seeds the supplement-db session store so the dashboard renders immediately.
 * Includes aging (submitted/unpaid, older) records to exercise aging alerts.
 */
import type { SupplementRecord } from '@/components/supplements/types';

export const MOCK_SUPPLEMENTS: SupplementRecord[] = [
  {
    id: 'sup-2044',
    roId: 'RO-2044',
    customerName: 'Priya Nair',
    vehicleInfo: '2019 Tesla Model 3',
    insuranceCarrier: 'Allstate',
    claimNumber: 'AL-902551',
    lifecycleStatus: 'DRAFT',
    createdAt: '2026-07-23T15:00:00.000Z',
    carrierNotes: '',
    totalDeltaAmount: 160,
    items: [
      {
        id: 'si-2044-1',
        description: 'Trunk lid hail dents (add’l)',
        category: 'PDR_LABOR',
        originalCost: 0,
        requestedCost: 160,
        status: 'PENDING',
      },
    ],
  },
  {
    id: 'sup-2051',
    roId: 'RO-2051',
    customerName: 'Dana Whitfield',
    vehicleInfo: '2021 Ford F-150',
    insuranceCarrier: 'State Farm',
    claimNumber: 'SF-771204',
    lifecycleStatus: 'SUBMITTED',
    createdAt: '2026-07-02T10:30:00.000Z',
    carrierNotes: 'Submitted with light-board photos; awaiting desk review.',
    totalDeltaAmount: 448,
    items: [
      {
        id: 'si-2051-1',
        description: 'Bumper retainer clips (qty 12)',
        category: 'CLIP_FASTENER',
        originalCost: 0,
        requestedCost: 48,
        status: 'PENDING',
        photoUrl: 'https://picsum.photos/seed/clips2051/240',
      },
      {
        id: 'si-2051-2',
        description: 'Additional roof hail dents — 45 add’l',
        category: 'PDR_LABOR',
        originalCost: 320,
        requestedCost: 540,
        status: 'PENDING',
      },
      {
        id: 'si-2051-3',
        description: 'Headliner R&I for roof access',
        category: 'R_I_LABOR',
        originalCost: 0,
        requestedCost: 180,
        status: 'PENDING',
      },
    ],
  },
  {
    id: 'sup-2062',
    roId: 'RO-2062',
    customerName: 'Sam Okoye',
    vehicleInfo: '2021 Ford F-150',
    insuranceCarrier: 'Allstate',
    claimNumber: 'AL-660118',
    lifecycleStatus: 'APPROVED_PENDING_PAYMENT',
    createdAt: '2026-06-20T09:00:00.000Z',
    carrierNotes: 'Approved on supplement #2; payment issued to shop pending.',
    totalDeltaAmount: 791,
    items: [
      {
        id: 'si-2062-1',
        description: 'Aluminum hood — unpainted edge damage found on teardown',
        category: 'PARTS',
        originalCost: 0,
        requestedCost: 690,
        status: 'APPROVED',
        photoUrl: 'https://picsum.photos/seed/hood2062/240',
      },
      {
        id: 'si-2062-2',
        description: 'Additional clear / blend materials',
        category: 'MATERIALS',
        originalCost: 45,
        requestedCost: 120,
        status: 'APPROVED',
      },
      {
        id: 'si-2062-3',
        description: 'Cowl fasteners',
        category: 'CLIP_FASTENER',
        originalCost: 0,
        requestedCost: 26,
        status: 'APPROVED',
      },
    ],
  },
  {
    id: 'sup-2039',
    roId: 'RO-2039',
    customerName: 'Grace Lin',
    vehicleInfo: '2020 Honda Accord',
    insuranceCarrier: 'GEICO',
    claimNumber: 'GC-559810',
    lifecycleStatus: 'PAID',
    createdAt: '2026-06-10T14:00:00.000Z',
    carrierNotes: 'Paid via EFT 2026-06-28.',
    totalDeltaAmount: 90,
    items: [
      {
        id: 'si-2039-1',
        description: 'Grille tab repair',
        category: 'PARTS',
        originalCost: 0,
        requestedCost: 90,
        status: 'APPROVED',
      },
    ],
  },
  {
    id: 'sup-2070',
    roId: 'RO-2070',
    customerName: 'Victor Reyes',
    vehicleInfo: '2021 BMW 330i',
    insuranceCarrier: 'Farmers',
    claimNumber: 'FM-620914',
    lifecycleStatus: 'SUBMITTED',
    createdAt: '2026-07-21T11:20:00.000Z',
    carrierNotes: '',
    totalDeltaAmount: 62,
    items: [
      {
        id: 'si-2070-1',
        description: 'Mirror R&I',
        category: 'R_I_LABOR',
        originalCost: 0,
        requestedCost: 40,
        status: 'PENDING',
      },
      {
        id: 'si-2070-2',
        description: 'Door panel clips',
        category: 'CLIP_FASTENER',
        originalCost: 0,
        requestedCost: 22,
        status: 'PENDING',
      },
    ],
  },
];
